### ISSUE TITLE
Doesn't account for routes.yaml

### ISSUE THREAD

**Issue by kevnk** [Marbles/statamic-sitemap#11]
I have several pages that are dynamically built (e.g. pages that list collection items) using `site/settings/routes.yaml`: https://docs.statamic.com/routing

Here's my `routes.yaml` for a real-life example:

```yaml
routes:
  /portal/talks:
    layout: portal
    template: portal/talks
    protect:
      type: logged_in
      login_url: /login
      append_redirect: true
  /latest:
    template: latest
  /login:
    template: login
  /contact:
    template: contact
  /events:
    template: events
  /talks:
    template: talks
  /testimonies:
    template: testimonies
  /blog:
    template: blog
collections:
  /blog/{year}/{month}/{slug}:
    template: default
  /talks/{year}/{month}/{slug}:
    template: default
  /events/{year}/{month}/{slug}:
    template: default
taxonomies: [ ]
redirect: [ ]
vanity: [ ]
```

The generated `/sitemap.xml` doesn't contain any of these urls.
